sudo: required
dist: trusty
language: node_js
env:
  global:
    secure: FwqnbdpZu7gPkRU+pbWy8OGblsG7amJdDqA6xtTBFiTots9aXaecJy+Z2jnA7tyzuelhRQ4zzSVVM1013RDQG14tyAdm5Rl912BpwrCRSd6lPtHylxLovnZdZtNCNWBbudeu8yDgzzhFPRvVFUpxU/J1LnQkcLyjuBHKry7qazHC3JIgV5phKr9c1a3HLRtRxmtZia8IzsiQsXYPKwiUU3bfRJ8fJQbbXOKv2xtaS55Spk6NxeYo0NyoEeu50ld8rqbdnEkbt/Go4jOpKZr4BvqHYGUHeDXdsxAwOE/401lOW9GcG1yhXKcm1T/LBj7WN+iD08/ZQmG8V1Q0rgr7Is3V2kjQhRBeniPqup6mn8PvquahT9qKmSqwM5GEGxv2gtAqhYHh36cpClIAxbWAM/Bgv/2uqw6lzSbVysWtgJ7rpeyi3C3y+LKGi7nHxkVm2Zo3N9aLqkloJPVo84Kev1PWJR+j8KCWFErZ1ya5QDzi+krziS2Dx5UFlyrxM9qI3ITDTck+BgpCepuZLz/PAHhxJ9V5GRieKHfXSQ1Qs70SFUkta+6RnSz2SZKSVwEk3X4uva4aJJfR21++jEyFB5WowFRRtVNwMcLja6B3FuTKgOHG8+A11UyFDBfQuiZvU9/nspqaGm4W7HdcSaMXTPTsMjjVlqePxmNr7Uir6BQ=
matrix:
  include:
  - os: osx
    node_js: 6
  - os: linux
    node_js: 6
    env: CC=clang CXX=clang++ npm_config_clang=1
    compiler: clang
cache:
  directories:
  - node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"
before_script:
- npm prune
after_success:
- npm run dist
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
