sudo: required
dist: trusty

language: node_js

matrix:
  include:
    - os: osx
      node_js: 6

cache:
  directories:
    - node_modules
    - $HOME/.electron
    - $HOME/.cache

before_script:
  - npm prune

after_success:
  - npm run dist

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
