sudo: required

dist: trusty

language: node_js

env:
  global:
    - secure: k1u5aITWIBDizTY7oY+DB0tS3NlqsJAo5jdu/ReEyo6f+FJfl7G+FHS4Cu0cGzZu/g9uBDAxiAP9WKuN/8F3fnnEkTL+kBcMDnvCySJtTx1Fj/QSHKt98PgSFdY5UQuOXlBcbTijL3Hz6rKhXo2N5f8qkxxsaNn5b2q1xd/+sGtGJqmK9sFg3czBdR74W3A+hX2Wa5hJYKJVmw52JNoMIuGxEEJiekCJ/3S6LfhgAmXD3tARWdPMIZEYFRXOOZmJ8bnyx6KtrqH8V28RBMqeALyyUie/wUA7CGYuFlc3bCvHc6VHJ/Nl1hMMparuCcMozE6qhCC7JbtGfD0SlZy0I/5X6+QFg7ExeUBkr58gIZETUQpVQ9zU7Ug0aGOU6ya/02iwfMxjqDJpbDAO/zkjWAKVngq8fkdudQj7CIJ038BdAhljnQScOB/gWBkKP1nB6UA3onyAOLxPokveCjji8VlaITotmV9qWcJ93oBkP8rTZoSjP1p4ffNMhenZvOqv1tBqc2PkK1th2TOcUBjy4oEVGTZ6T77EOcrXH1YUuE6ddqAhC9AM27gqihn56D9FrUlj5Qty928IsOP73Xcccr3AuRYSwn5Q+g2N/TTB3QramVcZjQt+zwSD7wZzWZhiIXmqD3ZuUwSZpxHs8/1mtD2IZNl38zTI7PeUtQhyzXs=

matrix:
  include:
  - os: osx
    node_js: 6
  - os: linux
    node_js: 6
    env: CC=clang CXX=clang++ npm_config_clang=1
    compiler: clang

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
  - node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"

before_script:
- npm prune

after_success:
- npm run dist
- NODE_ENV=production

branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
