environment:
  matrix:
    - platform: x64
  GH_TOKEN:
    secure: 1cWm5j4ljdD+w6LLOv24rbj1ON4cbrT49CQype/BCQLtM5sjnD3x83wpIqFhexM9

image: Visual Studio 2015

cache:
  - node_modules

install:
  - ps: Install-Product node 6 x64
  - set CI=true
  - npm -g install npm@latest
  - npm install

build: off

shallow_clone: true

test_script:
  - node --version
  - npm --version

on_success:
  - npm run dist
